/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GMN_Tarea2;

import javax.swing.JOptionPane;

/**
 *
 * @author Aguilera Luzania José Luis.
 * @author Castro Márquez Francisco Javier.
 * @author Monge Tinoco Manuel Crisólogo.
 */
public class ControlPanel extends javax.swing.JPanel {
    
    
    // Constantes para los casos.
    private final int NEWTON_RAPHSON = 0, BISECCION = 1;
    
    /** ATRIBUTOS DE LA CLASE **/
    private final double errorDeTruncamientoDefault = 0.0005;
            
    private MainWindow window;
    private MainPanel mainPanel;

    
    /** CONSTRUCTOR **/
    public ControlPanel()
    {
        initComponents();
        
       EstablecerCamposParaElMetodo(NEWTON_RAPHSON);
    }
    
    // Inicio Función inicia ------------------------------------------------------------------------
    public void inicia(MainWindow _window, MainPanel _mainPanel)
    {
        this.window = _window;
        this.mainPanel = _mainPanel;
    }
    // Fin Función inicia ---------------------------------------------------------------------------
    
    
    // Inicio Función EstablecerCamposParaElMetodo --------------------------------------------------
    private void EstablecerCamposParaElMetodo(int _metodo)
    {
        switch (_metodo) {
            
            case NEWTON_RAPHSON:
                
                LimpiarCampos();
                tfx0.setEditable(true);
                tfa.setEditable(false);
                tfb.setEditable(false);
                tfError.setEditable(false);
                break;
                
            case BISECCION:
                
                LimpiarCampos();
                tfa.setEditable(true);
                tfb.setEditable(true);
                tfError.setEditable(true);
                tfx0.setEditable(false);
                tfError.setText( Double.toString(errorDeTruncamientoDefault) );
                break;
        }
    }
    // Fin Función EstablecerCamposParaElMetodo -----------------------------------------------------
    
    // Inicio Función LimpiarCampos -----------------------------------------------------------------
    private void LimpiarCampos()
    {
        tfx0.setText("");
        tfa.setText("");
        tfb.setText("");
        tfError.setText("");
        tfRaiz.setText("");
    }
    // Fin Función LimpiarCampos --------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMetodo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfb = new javax.swing.JTextField();
        tfx0 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfRaiz = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfError = new javax.swing.JTextField();
        etiqueta_titulo = new java.awt.Label();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setText("Métodos");

        jLabel2.setText("Intervalo [a, b]");

        cbMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N-R", "Biseccion" }));
        cbMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodoActionPerformed(evt);
            }
        });

        jLabel4.setText("a:");

        jLabel5.setText("b:");

        jLabel6.setText("X0:");

        jLabel8.setText("Xs:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Raíz (Mejor aproximación)");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel7.setText("Error:");

        etiqueta_titulo.setAlignment(java.awt.Label.CENTER);
        etiqueta_titulo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        etiqueta_titulo.setText("Aproximación de raíces");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Datos Bisección");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Datos Newton-Raphson");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Error de truncamiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfb)
                            .addComponent(tfa)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRaiz))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfError, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfx0))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(etiqueta_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMetodo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfx0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfRaiz)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        etiqueta_titulo.getAccessibleContext().setAccessibleName("Aproximacion de raices");
    }// </editor-fold>//GEN-END:initComponents

    private void cbMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodoActionPerformed
        EstablecerCamposParaElMetodo(cbMetodo.getSelectedIndex());
    }//GEN-LAST:event_cbMetodoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        try {      
            // Creamos una variable donde guardar la raíz encontrada.
            double x_s;
            
            // Aplicamso el método según la elección del usuario.
            switch (cbMetodo.getSelectedIndex()) {
                
                // -------------------------------------------------------------------------
                case NEWTON_RAPHSON:
                    
                    // Obtenemos nuestra x inicial
                    String x0Str = tfx0.getText();
                    double x0 = Double.parseDouble(x0Str);
                    
                    // Aplicamos newton-raphson para obtener la raíz y truncamos a sólo 5 sifras significativas.
                    x_s = Utileria.TruncarSignificativos( MetodosNumericos.NewtonRaphson(x0) , 5);
                    
                    // Definimos x_s en la gráfica.
                    this.mainPanel.DibujarRaiz(x_s);
                    
                    // Escribimos nuestra x_s en el textField.
                    tfRaiz.setText( Double.toString(x_s) );
                    
                    break;
                    
                // -------------------------------------------------------------------------
                case BISECCION:
                    
                    // Obtenemos el error de truncamiento.
                    String errorDeTruncamientoStr = tfError.getText();    
                    double errorDeTruncamiento = Double.parseDouble(errorDeTruncamientoStr);

                    // Si el error de truncamiento es cero o menor, entonces usamos un valor predefinido.
                    if (errorDeTruncamiento < 0)
                        errorDeTruncamiento = errorDeTruncamientoDefault;
                    
                    // Obtenemos los extremos del intervalo.
                    String aStr = tfa.getText();
                    String bStr = tfb.getText();
                    
                    double a = Double.parseDouble(aStr);
                    double b = Double.parseDouble(bStr);
                    
                    // Aplicamos bisección para obtener la raíz y truncamos a sólo 5 cifras significativas.
                    x_s = Utileria.TruncarSignificativos( MetodosNumericos.Biseccion(a, b, errorDeTruncamiento) , 5);
                    
                    // Definimos x_s en la gráfica.
                    this.mainPanel.DibujarRaiz(x_s);
                    
                    // Escribimos nuestra x_s en el textField.
                    tfRaiz.setText( Double.toString(x_s) );
                    
                    break;
                    
                // -------------------------------------------------------------------------
                default:
                    JOptionPane.showMessageDialog(this, "ERROR: La elección no corresponde a ningun método numérico.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(this, "Revise las entradas, los datos podría ser no numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado, contacte con el programador por favor.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbMetodo;
    private java.awt.Label etiqueta_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfError;
    private javax.swing.JTextField tfRaiz;
    private javax.swing.JTextField tfa;
    private javax.swing.JTextField tfb;
    private javax.swing.JTextField tfx0;
    // End of variables declaration//GEN-END:variables
}
