package panels;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import gmn.VentanaPrincipal;
import aproximacion.Aproximacion;

/**
 *
 * @author Aguilera Luzania José Luis.
 * @author Castro Márquez Francisco Javier.
 * @author Monge Tinoco Manuel Crisólogo.
 */
public class PanelConfig extends javax.swing.JPanel {

    private final int BISECCION = 0;
    private final int NEWTON_RAPHSON = 1;
    private final double ERROR_TRUNC_DEFAULT = 0.0005;

    private PanelGrafica panelGrafica;

    /**
     * Crea un nuevo Panel de configuración
     */
    public PanelConfig() {
        initComponents();
        habilitarCamposPara(BISECCION);
    }

    public void crear(PanelGrafica nuevoPanelGrafica) {
        panelGrafica = nuevoPanelGrafica;
    }

    private void limpiarCampos() {
        aTF.setText("");
        bTF.setText("");
        eTF.setText("");
        xTF.setText("");
        resultadoTF.setText("");
    }

    private void habilitarCamposPara(int metodo) {
        switch (metodo) {
            case BISECCION:
                limpiarCampos();
                aTF.setEditable(true);
                bTF.setEditable(true);
                eTF.setEditable(true);
                eTF.setText(Double.toString(ERROR_TRUNC_DEFAULT));
                xTF.setEditable(false);
                break;

            case NEWTON_RAPHSON:
                limpiarCampos();
                aTF.setEditable(false);
                bTF.setEditable(false);
                eTF.setEditable(false);
                xTF.setEditable(true);
                break;
        }
    }

    private double truncarSignificativos(double numero, int cifras_sign) {
        try {
            String auxiliar = Double.toString(numero);
            auxiliar = auxiliar.substring(0, auxiliar.indexOf('.') + cifras_sign + 1);

            return Double.parseDouble(auxiliar);

        } catch (NumberFormatException e) {
            return numero;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        metodoCbx = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        datosBiseccionTxt = new javax.swing.JLabel();
        datosNewtonTxt = new javax.swing.JLabel();
        metodoLbl = new javax.swing.JLabel();
        aTxt = new javax.swing.JLabel();
        aTF = new javax.swing.JTextField();
        ejemploIntervaloTxt = new javax.swing.JLabel();
        bTxt = new javax.swing.JLabel();
        bTF = new javax.swing.JTextField();
        errorTxt = new javax.swing.JLabel();
        eTF = new javax.swing.JTextField();
        x0Txt = new javax.swing.JLabel();
        xTF = new javax.swing.JTextField();
        calcularBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        resultadoTxt = new javax.swing.JLabel();
        eTxt = new javax.swing.JLabel();
        resultadoTF = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(230, 230, 230));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setFont(new java.awt.Font("Input", 0, 12)); // NOI18N

        headerLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        headerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLbl.setText("CONFIGURACIÓN");

        metodoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bisección", "Newton" }));
        metodoCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoCbxActionPerformed(evt);
            }
        });

        datosBiseccionTxt.setFont(new java.awt.Font("Input", 1, 12)); // NOI18N
        datosBiseccionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosBiseccionTxt.setText("Datos bisección");
        datosBiseccionTxt.setToolTipText("");

        datosNewtonTxt.setFont(new java.awt.Font("Input", 1, 12)); // NOI18N
        datosNewtonTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosNewtonTxt.setText("Datos newton-raphson");
        datosNewtonTxt.setToolTipText("");

        metodoLbl.setFont(new java.awt.Font("Input", 1, 12)); // NOI18N
        metodoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        metodoLbl.setText("Método");
        metodoLbl.setToolTipText("");

        aTxt.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        aTxt.setText("a:");

        aTF.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        aTF.setText("-5.0");
        aTF.setToolTipText("Extremo inferior del intervalo.");

        ejemploIntervaloTxt.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        ejemploIntervaloTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ejemploIntervaloTxt.setText("[a,b]");
        ejemploIntervaloTxt.setToolTipText("");

        bTxt.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        bTxt.setText("b:");

        bTF.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        bTF.setText("5.0");
        bTF.setToolTipText("Extremo superior del intervalo.");

        errorTxt.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        errorTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorTxt.setText("Error de truncamiento");
        errorTxt.setToolTipText("");

        eTF.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        eTF.setText("0.0005");
        eTF.setToolTipText("Valor del error de truncamiento.");
        eTF.setPreferredSize(new java.awt.Dimension(170, 22));

        x0Txt.setText("X_0:");

        xTF.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        xTF.setText("1");
        xTF.setToolTipText("Valor inicial de X");
        xTF.setPreferredSize(new java.awt.Dimension(170, 22));

        calcularBtn.setText("Calcular");
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        resultadoTxt.setFont(new java.awt.Font("Input", 1, 12)); // NOI18N
        resultadoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoTxt.setText("Mejor aproximación");
        resultadoTxt.setToolTipText("");
        resultadoTxt.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        eTxt.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        eTxt.setText("e:");

        resultadoTF.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        resultadoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultadoTF.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ejemploIntervaloTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metodoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datosBiseccionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(eTxt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(xTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calcularBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(resultadoTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bTxt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bTF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aTxt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aTF))
                                    .addComponent(headerLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator2)
                                    .addComponent(metodoCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)
                                    .addComponent(resultadoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(errorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x0Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(datosNewtonTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metodoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metodoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datosBiseccionTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejemploIntervaloTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aTxt)
                    .addComponent(aTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTxt)
                    .addComponent(bTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(errorTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datosNewtonTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x0Txt)
                    .addComponent(xTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadoTxt)
                .addGap(5, 5, 5)
                .addComponent(resultadoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcularBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void metodoCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoCbxActionPerformed
        // TODO add your handling code here:
        habilitarCamposPara(metodoCbx.getSelectedIndex());
    }//GEN-LAST:event_metodoCbxActionPerformed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        // TODO add your handling code here:
        try {

            double xs = 0;

            switch (metodoCbx.getSelectedIndex()) {
                // -------------------------------------------------------------
                case NEWTON_RAPHSON:
                    double x0 = Double.parseDouble(xTF.getText());

                    xs = truncarSignificativos(Aproximacion.NewtonRaphson(x0), 5);

                    resultadoTF.setText(Double.toString(xs));
                    panelGrafica.graficarRaiz(xs);
                    break;

                // -------------------------------------------------------------
                case BISECCION:
                    double errorT = Double.parseDouble(eTF.getText());

                    if (errorT < 0) {
                        eTF.setText(Double.toString(ERROR_TRUNC_DEFAULT));
                        JOptionPane.showMessageDialog(
                                this,
                                "ERROR: El error de truncamiento no puede ser negativo",
                                "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }

                    double a = Double.parseDouble(aTF.getText());
                    double b = Double.parseDouble(bTF.getText());

                    if (!Aproximacion.hayCambioDeSigno(a, b)) {
                        JOptionPane.showMessageDialog(
                                this,
                                "ERROR: No hay cambio de signo en el intervalo: ["
                                + Double.toString(a) + ", " + Double.toString(a)
                                + "].",
                                "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }

                    xs = truncarSignificativos(
                            Aproximacion.Biseccion(a, b, errorT), 5);

                    panelGrafica.graficarRaiz(xs);
                    resultadoTF.setText(Double.toString(xs));
                    break;

                // -------------------------------------------------------------
                default:
                    JOptionPane.showMessageDialog(
                            this,
                            "ERROR: No se encontró el método seleccionado..",
                            "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Revise las entradas, los datos podrían ser no numéricos.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ocurrió un error inesperado, contacte con el programador.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calcularBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aTF;
    private javax.swing.JLabel aTxt;
    private javax.swing.JTextField bTF;
    private javax.swing.JLabel bTxt;
    private javax.swing.JButton calcularBtn;
    private javax.swing.JLabel datosBiseccionTxt;
    private javax.swing.JLabel datosNewtonTxt;
    private javax.swing.JTextField eTF;
    private javax.swing.JLabel eTxt;
    private javax.swing.JLabel ejemploIntervaloTxt;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> metodoCbx;
    private javax.swing.JLabel metodoLbl;
    private javax.swing.JTextField resultadoTF;
    private javax.swing.JLabel resultadoTxt;
    private javax.swing.JLabel x0Txt;
    private javax.swing.JTextField xTF;
    // End of variables declaration//GEN-END:variables
}
